In [48]:
# Domain – Education

# focus – Data analysis
# Business challenge/requirement
# You are a data analyst with University of Cal USA (Not a machine learning expert yet as you still have not completed ML with Python Course :-)).The University has data of Math, Physics and Data Structure score of sophomore students. This data is stored in different files. The University has hired a data science company to do analysis of scores and find if there is any correlation of score with age, ethnicity etc. Before the data is given to the company you have to do data wrangling.

# Key issues
# Ensure students identify is not revealed to the agency and only relevant data is shared

# Considerations
# NONE

# Data volume
# -	In thousands, but only around 1800 records are shared in files MathScoreTerm1.csv DSScoreTerm1.csv, PhysicsScoreTerm1.csv

# Additional information
# - NA
# Business benefits
# University can get more students enrollment by improving its international ranking through personalized course/curriculum for students

# Approach to Solve
# You have to use fundamentals of Numpy and Pandas.

# 1.	Read the three csv files which contains the score of same students in term1 for each Subject


import pandas as pd
ds_score=pd.read_csv("/content/DSScoreTerm1.csv")
math_score=pd.read_csv("/content/MathScoreTerm1.csv")
phy_score=pd.read_csv("/content/PhysicsScoreTerm1.csv")
final_score=pd.read_csv("/content/ScoreFinal.csv")

In [49]:
# 2.	Remove the name and ethnicity column (to ensure confidentiality)/

ds_score=ds_score.drop(columns=['Name','Ethinicity'])
math_score=math_score.drop(columns=['Name','Ethinicity'])
phy_score=phy_score.drop(columns=['Name','Ethinicity'])

In [50]:
# 3.	Fill missing score data with zero

# Maths Data
# print Summary of missing values in  Maths Data
print(math_score.isnull().sum())
# Fill Missing Scores with 0
math_score['Score']=math_score['Score'].fillna(0)
# Check Again if values are filled correctly
print(math_score.isnull().sum())


# Data Science Data
# print Summary of missing values in Data Science Data
print(ds_score.isnull().sum())
# Fill Missing Scores with 0
math_score['Score']=math_score['Score'].fillna(0)
# Check Again if values are filled correctly'
print(math_score.isnull().sum())

# Physics Data
# print Summary of missing values in Physics Data
print(ds_score.isnull().sum())
# Fill Missing Scores with 0
math_score['Score']=math_score['Score'].fillna(0)
# Check Again if values are filled correctly
print(math_score.isnull().sum())

Score      3
Age        0
Subject    0
Sex        0
ID         0
dtype: int64
Score      0
Age        0
Subject    0
Sex        0
ID         0
dtype: int64
Score      8
Age        0
Subject    0
Sex        0
ID         0
dtype: int64
Score      0
Age        0
Subject    0
Sex        0
ID         0
dtype: int64
Score      8
Age        0
Subject    0
Sex        0
ID         0
dtype: int64
Score      0
Age        0
Subject    0
Sex        0
ID         0
dtype: int64

In [51]:
# 4.	Merge the three files
# Merge all data - List is created
merged_data=[ds_score,math_score,phy_score]
merged_data=pd.concat(merged_data)
merged_data

     Score  Age        Subject Sex   ID
0     82.0   18  Data Structue   M    1
1     79.0   19  Data Structue   M    2
2     39.0   19  Data Structue   M    3
3     76.0   18  Data Structue   M    4
4     76.0   18  Data Structue   F    5
..     ...  ...            ...  ..  ...
594   41.0   19        Physics   F  595
595   71.0   18        Physics   M  596
596   49.0   20        Physics   M  597
597   71.0   20        Physics   M  598
598   69.0   19        Physics   M  599

[1797 rows x 5 columns]

In [52]:
# 5.	Change Sex(M/F) Column to 1/2 for further analysis
# Convert Sex M to 1 and F to 2

merged_data['Sex']=merged_data['Sex'].replace({'M':1,'F':2})
merged_data

/tmp/ipykernel_3256/1007619168.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged_data['Sex']=merged_data['Sex'].replace({'M':1,'F':2})

     Score  Age        Subject  Sex   ID
0     82.0   18  Data Structue    1    1
1     79.0   19  Data Structue    1    2
2     39.0   19  Data Structue    1    3
3     76.0   18  Data Structue    1    4
4     76.0   18  Data Structue    2    5
..     ...  ...            ...  ...  ...
594   41.0   19        Physics    2  595
595   71.0   18        Physics    1  596
596   49.0   20        Physics    1  597
597   71.0   20        Physics    1  598
598   69.0   19        Physics    1  599

[1797 rows x 5 columns]

In [53]:
# 6.	Store the data in new file – ScoreFinal.csv
merged_data.to_csv("Final_score.csv")